=== StarRaul/Proiecte-VSC/Proiect-xml/src/xml/leaderboards.dtd
<!ELEMENT leaderboards (metadata, users, games, messages)>

<!ELEMENT metadata (title, description, formula, logo)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT formula ANY>
<!ELEMENT logo ANY>

<!ELEMENT users (user+)>
<!ELEMENT user (username, password)>
<!ATTLIST user
    id CDATA #REQUIRED
    role (admin|user) #REQUIRED
>
<!ELEMENT username (#PCDATA)>
<!ELEMENT password (#PCDATA)>

<!ELEMENT games (game+)>
<!ELEMENT game (n, image, description, placements)>
<!ATTLIST game
    id ID #REQUIRED
>
<!ELEMENT n (#PCDATA)>
<!ELEMENT image (#PCDATA)>
<!ELEMENT placements (placement*)>
<!ELEMENT placement (imagine, scor, nume)>
<!ATTLIST placement
    id CDATA #REQUIRED
>
<!ELEMENT imagine (#PCDATA)>
<!ELEMENT scor (#PCDATA)>
<!ELEMENT nume (#PCDATA)>

<!ELEMENT messages (message*)>
<!ELEMENT message (name, email, mesaj)>
<!ATTLIST message
    id CDATA #REQUIRED
>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT mesaj (#PCDATA)>

<!ELEMENT math ANY>
<!ATTLIST math xmlns CDATA #IMPLIED>
<!ELEMENT mrow ANY>
<!ELEMENT mi (#PCDATA)>
<!ELEMENT mo (#PCDATA)>
<!ELEMENT mfrac ANY>

<!ELEMENT svg ANY>
<!ATTLIST svg 
    xmlns CDATA #IMPLIED 
    viewBox CDATA #IMPLIED 
    width CDATA #IMPLIED 
    height CDATA #IMPLIED
>
<!ELEMENT circle ANY>
<!ATTLIST circle 
    cx CDATA #IMPLIED 
    cy CDATA #IMPLIED 
    r CDATA #IMPLIED 
    fill CDATA #IMPLIED 
    stroke CDATA #IMPLIED 
    stroke-width CDATA #IMPLIED
>
<!ELEMENT polygon ANY>
<!ATTLIST polygon 
    points CDATA #IMPLIED 
    fill CDATA #IMPLIED
>

=== StarRaul/Proiecte-VSC/Proiect-xml/src/xml/leaderboards.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="leaderboards.xsl"?>
<!DOCTYPE leaderboards SYSTEM "leaderboards.dtd">
<leaderboards>
  <metadata>
    <title>Game Leaderboards</title>
    <description>Top scores for Alan Wake 2, Resident Evil 4 and Titanfall 2.</description>
    <formula>
      <math xmlns="http://www.w3.org/1998/Math/MathML">
        <mrow>
          <mi>Rank</mi>
          <mo>=</mo>
          <mfrac>
            <mrow>
              <mi>Score</mi>
              <mo>×</mo>
              <mi>Difficulty</mi>
            </mrow>
            <mi>Time</mi>
          </mfrac>
        </mrow>
      </math>
    </formula>
    <logo>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="80" height="80">
        <circle cx="50" cy="50" r="45" fill="#1a1a2e" stroke="#ffffff" stroke-width="2"/>
        <polygon points="50,20 65,45 80,45 68,60 73,80 50,67 27,80 32,60 20,45 35,45" fill="#ffffff"/>
      </svg>
    </logo>
  </metadata>
  <users>
    <user id="1" role="admin">
      <username>admin</username>
      <password>admin</password>
    </user>
    <user id="2" role="user">
      <username>raul</username>
      <password>abcd</password>
    </user>
    <user id="3" role="user">
      <username>stefan</username>
      <password>1234</password>
    </user>
  </users>
  <games>
    <game id="alanwake">
      <n>Alan Wake 2</n>
      <image>images/alanwake2.jpg</image>
      <description>View top scores in completing Alan Wake's story</description>
      <placements>
        <placement id="1">
          <imagine>./images/1774861616_7381.jpg</imagine>
          <scor>123</scor>
          <nume>admin</nume>
        </placement>
        <placement id="2">
          <imagine>./images/1774861621_4484.jpg</imagine>
          <scor>456</scor>
          <nume>admin</nume>
        </placement>
      </placements>
    </game>
    <game id="residentevil">
      <n>Resident Evil 4</n>
      <image>images/residentevil.jpg</image>
      <description>View top scores in accomplishing Leon S. Kennedy's mission</description>
      <placements/>
    </game>
    <game id="titanfall">
      <n>Titanfall 2</n>
      <image>images/titanfall.jpg</image>
      <description>View top scores in Jack Cooper's attempt to stop the opposing forces</description>
      <placements/>
    </game>
  </games>
  <messages/>
</leaderboards>
